// Generated by https://quicktype.io

export interface VolumeInfo {
  id: number;
  bookId: number;
  title: String;
  authors: String;
  publisher: String;
  publishedDate: String;
  description: String;
  industryIdentifiers: Array<any>;
  pageCount: String
  categories: Array<String>;
  maturityRating: String
  language: String;
}
